CREATE TABLE IF NOT EXISTS perfis(
id BIGSERIAL PRIMARY KEY NOT NULL,
nome VARCHAR(45) NOT NULL UNIQUE,
ativo BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS cursos(
id BIGSERIAL PRIMARY KEY NOT NULL,
nome VARCHAR(45) NOT NULL ,
categoria VARCHAR(45) NOT NULL,
ativo BOOLEAN DEFAULT TRUE
);


CREATE TABLE IF NOT EXISTS usuarios(
id BIGSERIAL PRIMARY KEY NOT NULL ,
nome VARCHAR(45) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
senha VARCHAR(255) NOT NULL,
ativo BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS topicos(
id BIGSERIAL PRIMARY KEY NOT NULL,
titulo VARCHAR(45) NOT NULL,
mensagem VARCHAR(45) NOT NULL,
data_criacao TIMESTAMP NULL,
status_topico VARCHAR(45) NULL,
ativo BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS respostas(
id BIGSERIAL PRIMARY KEY NOT NULL,
mensagem VARCHAR(45) NOT NULL,
data_criacao TIMESTAMP NOT NULL,
solucao VARCHAR(255) NOT NULL
);
